version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ['nodejs']
  plugins = ['react', 'vue']
  dialect = 'flow'
  dependency_file_paths = [
    'packages/demo-react/',
    'packages/demo-vue/',
    'packages/demo-next/',
    'packages/demo-nuxt/',
    'packages/demo-typescript/'
  ]
  style_guide = "airbnb"


[[transformers]]
    name = "prettier"
    enabled = true

[[analyzers]]
name = "secrets"
enabled = true
